### ISSUE TITLE
tabel nummeraanduiding heeft soms referentie naar woonplaats

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#137]
Normaal wordt een adres verkregen via nummeraanduiding naar openbare ruimte en dan woonplaats. In sommige gevallen ligt een verblijfsobject aan een openbare ruimte waar de gemeentegrens over de oprit loopt. In dat geval wordt bij de nummeraanduiding de woonplaats opgenomen.
Eigenlijk moeten alle views worden aangepast om met deze uitzondering rekening te houden.

**Comment by cvanlith** [comment]
Als fk_6wpl_identif in addresseerb_obj_aand is NOT NULL dan ligt pand in andere gemeente en moet die woonplaats genoemd worden bij het volledige adres en niet de woonplaats die bij de openbare ruimte staat.

**Comment by mprins** [comment]
in een recente BAG gaat het om 1693 nummeraanduidingen
