### ISSUE TITLE
Adresselectie via puntgeometrie VBO is niet correct

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#143]
Op dit moment wordt in de adres-view de puntgeometrie van een VBO gezien wordt als ‘de locatie van het adres’.

Dat is niet helemaal juist: de view levert de puntgeometrie van het verblijfsobject (een adres zelf heeft geen locatie) waarbij de kanttekening is, dat de BAG voorschrijft, dat deze puntgeometrie ‘ergens’ binnen het bijbehorende pand moet liggen (niet per sé op de juiste plek). In een flatgebouw kan dat flink verschillen van de echte locatie.

Dat betekent bijvoorbeeld, dat voor het maken van een adreslijst binnen een polygoon er (als je het goed doet) geen gebruik kan worden gemaakt van deze puntgeometrie, maar er altijd naar de pandgeometrie moet worden gekeken, waarna alle verblijfsobjecten/adressen binnen het pand worden gezocht.

Het is daarom het enigszins misleidend in een adresview geometrie op te nemen alsof dat de geometrie van het adres is.

**Comment by cvanlith** [comment]
Het beste via panden de VBO's selecteren. Ook rekening houden met ligplaatsen en standaplaatsen?

**Comment by mprins** [comment]
`v_adres_totaal` is union van (`v_adres`+`v_adres_ligplaats`+`v_adres_standplaats`)

| view | geom kolom 1 | geom kolom 2 | geom in `v_adres_totaal` |
| ---- | ---- | ---- | ---- |
|`v_adres`                     |`gebouwd_obj.puntgeom` |     | 1 |
|`v_adres_ligplaats`      |`benoemd_terrein.geom`  |centroide `benoemd_terrein.geom`  | 2 |
|`v_adres_standplaats` |`benoemd_terrein.geom`  |centroide `benoemd_terrein.geom`  | 2 |

`v_adres` zou evt. ook `gebouwd_obj.vlakgeom` kunnen meenemen, ware het niet dat dit leeg is en als er een tweede geometrie kolom wordt toegevoegd dan kan deze view niet meer in arcgis worden gebruikt.
