### ISSUE TITLE
Uitleg bij Planning (cron expressie) is onvolledig 

### ISSUE THREAD

**Issue by NiekBouma** [B3Partners/brmo#145]
Als je in de planning 0 40 11 1/1 *?* , dus iedere dag om 11:40 h, dan verschijnt erachter in de brmo-service:
"Om 11:;40, elke jaar".

Is het mogelijk om er ook de informative over de dagen bij te zetten en er 'elk jaar' van te maken?

**Comment by mprins** [comment]
we gebruiken de [cron-parser library](https://github.com/RedHogs/cron-parser/); de "elke jaar" is opgelost in de nieuwe versie die in 20aa48e79c8c8c179c7c410a0bb4ec1d05332b65 is ingevoegd, dus dat zit in de volgende release. 

Staat er echt `Om 11:;40, elke jaar` dus met die `;`?

Overigens, de correcte expressie is `0 40 11 1/1 * ? *`

**Comment by NiekBouma** [comment]
nee, die ; is een typo

**Comment by mprins** [comment]
opened RedHogs/cron-parser#34
