### ISSUE TITLE
Sending BRMO-messages by SKP works very slow

### ISSUE THREAD

**Issue by NiekBouma** [B3Partners/brmo#183]
Sending BRMO-messages by SKP to the customer works very slow (2-3 seconds for 1 message). Sending for example 5.000 messages takes 40 minutes, and the time needed per message rises substantially over time. I looks like the capacity is reached at some point.
This occurs in BRMO Proxy when accepting messages from SKP en writing them out to disk. This is not writing to the staging database.

**Comment by mprins** [comment]
De proxy service heeft geen limiet mechanisme, als er zoiets optreed zit dat in de servletcontainer,  webserver of netwerk config of server.

**Comment by mprins** [comment]
@NiekBouma is hier nog meer over bekend? (debug) logfiles van skp (zender) en de ontvanger bijvoorbeeld.. en/of schijfruimte verbruik van de ontvanger
