### ISSUE TITLE
esri `objectid` aan views toevoegen

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#202]
Een aantal views heeft geen veld dat door esri software als `objectid` herkend of gebruikt kan worden;
- [x] uitzoeken wat de voorwaarde is voor een `objectid` veld
- [x] views aanpassen #229

**Comment by mprins** [comment]
http://webhelp.esri.com/arcgisserver/9.3/java/index.htm#geodatabases/geodata-953061022.htm

> ## Object Identifiers
> 
> The ObjectID field is maintained by ArcGIS and guarantees a unique ID for each row in the table. When you look at a table or a layer's attribute table, you will usually see the ObjectID field listed under the aliases of OID or ObjectID for tables and FID for layers. Key functions, such as scrolling and displaying selection sets, depend on the presence of this field.
It should be noted that most ArcGIS Desktop functionality, such as using the identify tool, requires the ObjectID to be unique. Therefore, caution should be used when working directly with the database so that ObjectIDs are not duplicated. For example, when creating views with a one-to-many relationship, there is the possibility that ObjectIDs will be duplicated. This will cause inconsistent behavior in ArcGIS Desktop functionality.

**Comment by mprins** [comment]
http://desktop.arcgis.com/en/arcmap/10.3/manage-data/using-sql-with-gdbs/object-id.htm

> ## What is an ObjectID?
>
> An ObjectID is a unique, not null integer field used to uniquely identify rows in tables in a geodatabase. ObjectIDs are limited to 32-bit values, which store a maximum value of 2,147,483,647.
>
>Tables that are created through ArcGIS, or created outside ArcGIS then registered with the geodatabase, automatically have an ObjectID field added to them. The values in this field are maintained by ArcGIS. The ObjectID is used by ArcGIS to do such things as scroll, display selection sets, and perform identify operations on features.
>
> ## When is an ObjectID added to a table?
>
>There are several ways an ObjectID is added to a table:
>
>An ArcGIS-maintained ObjectID field is automatically added to any table created using ArcGIS.
If you register a table with the geodatabase that does not have a qualifying field, the geodatabase adds another field to the table that meets the requirements of an ObjectID and names it OBJECTID. If your table already contains a column that is named OBJECTID, the geodatabase adds a column named OBJECTID_1.
>If you register a table with the geodatabase and the table does contain a qualifying field (integer, not null), the existing column can be used as the ObjectID.

**Comment by mprins** [comment]
http://desktop.arcgis.com/en/arcmap/10.3/manage-data/gdbs-in-oracle/views-in-geodatabase.htm

**Comment by mprins** [comment]
In tabel `KAD_ONRRND_ZK` wordt `KAD_IDENTIF NUMBER(15) NOT NULL` (oracle) gebruikt, hoewel uniek en not null is dat geen 32-bit int volgens esri

### oracle 
gebruik `TT_INTEGER` of `NUMBER(38,0)`

### postgresql

### sqlserver

uiteindelijk hebben we arcgis nodig om dit te testen..

**Comment by MannusEtten** [comment]
> verbinden met een oracle zonder sde schema lijkt niet mogelijk op de test omgeving (arcgis 10.4.1 + oracle 11g)

in ArcGIS 10.4 met Oracle 11g kan het prima. Komt het door de patch?

database connection maken in ArcCatalog, instance opgeven in vorm als dit :"//localhost:1521/orcl.work.local"

**Comment by mprins** [comment]
@MannusEtten Welke patch? Ik heb de actuele evaluatie versie gedownload; mogelijk zit er een bug in arcgis (maar arcgis is niet ons product, laat staan mijn expertise, en evaluatie versies komen niet met een support contract); 

mijn oracle verbindings gegevens:
```
instance: 192.168.1.202/ORCL
Authentication type: "database authentication"
```

Het eerste wat er lijkt te gebeuren bij het openen van de database verbinding is een call naar een procedure in het oracle schema:
![image](https://cloud.githubusercontent.com/assets/1165786/18546519/b08a49fc-7b3e-11e6-9b2f-1762908b9b4f.png)

met de gegevens zoals ik ze heb wordt wel een netwerk verbinding gemaakt, wat de melding ook impliceert, maar niet succesvol vanwege ontbreken van een sde procedure.

Ik heb dus geen stored procedure `sde.pinfo_util.get_sde_id` in mijn database...

Als ik er een dubbele slash voor zet dan maakt dat niet uit..

**Comment by MannusEtten** [comment]
poort meegeven? heb je een oracle client geinstalleerd? ik heb soortgelijke problemen niet ondervonden

**Comment by mprins** [comment]
het is duidelijk dat er een foutmelding uit de database terugkomt en ik zie ook de verbinding in het IP verkeer voorbij komen

**Comment by MannusEtten** [comment]
lastig om er iets van te zeggen, mede omdat ik de installatie niet ken. Maar iets met sde suggereert dat er ArcSDE in gebruik is, iets wat in mijn geval niet aan de orde is.

**Comment by mprins** [comment]
er is geen sde aan mijn kant; nooit geweest
