### ISSUE TITLE
Empty geometry results in array with null values in oracle

### ISSUE THREAD

**Issue by mtoonen** [B3Partners/brmo#221]

**Comment by mtoonen** [comment]
--select begrenzing_perceel, c.begrenzing_perceel.GET_GTYPE() from kad_perceel c where sc_kad_identif = 89020206140042 and begrenzing_perceel is not null
--select count(*) from kad_perceel c where c.begrenzing_perceel.GET_GTYPE() is null
--select * from kad_perceel p where k.begrenzing_perceel.GET_GTYPE() is not null

update WOZ_OBJ_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update BENOEMD_TERREIN c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update BUURT c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update FUNCTIONEEL_GEBIED c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update GEBOUWD_OBJ c set VLAKGEOM = null where c.VLAKGEOM.GET_GTYPE() IS NULL;
update GEBOUWD_OBJ c set PUNTGEOM = null where c.PUNTGEOM.GET_GTYPE() IS NULL;
update GEBOUWINSTALLATIE c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update GEMEENTE c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update INRICHTINGSELEMENT c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update KAD_PERCEEL c set BEGRENZING_PERCEEL = null where c.BEGRENZING_PERCEEL.GET_GTYPE() IS NULL;
update KAD_PERCEEL c set PLAATSCOORDINATEN_PERCEEL = null where c.PLAATSCOORDINATEN_PERCEEL.GET_GTYPE() IS NULL;
update KUNSTWERKDEEL c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update ONBEGR_TERR_DL c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update ONBEGR_TERR_DL c set KRUINLIJNGEOM = null where c.KRUINLIJNGEOM.GET_GTYPE() IS NULL;
update ONDERSTEUNEND_WEGDEEL c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update OVERIG_BOUWWERK c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update OVRG_SCHEIDING c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update PAND c set GEOM_BOVENAANZICHT = null where c.GEOM_BOVENAANZICHT.GET_GTYPE() IS NULL;
update PAND c set GEOM_MAAIVELD = null where c.GEOM_MAAIVELD.GET_GTYPE() IS NULL;
update SCHEIDING c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update SPOOR c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update STADSDEEL c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update VRIJSTAAND_VEGETATIE_OBJ c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WATERDEEL c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WATERSCHAP c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WEGDEEL c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WIJK c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WNPLTS c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WOZ_OBJ c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update BEGR_TERR_DL_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update BEGR_TERR_DL_ARCHIEF c set KRUINLIJNGEOM = null where c.KRUINLIJNGEOM.GET_GTYPE() IS NULL;
update BENOEMD_TERREIN_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update BUURT_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update FUNCTIONEEL_GEBIED_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update GEBOUWD_OBJ_ARCHIEF c set VLAKGEOM = null where c.VLAKGEOM.GET_GTYPE() IS NULL;
update GEBOUWD_OBJ_ARCHIEF c set PUNTGEOM = null where c.PUNTGEOM.GET_GTYPE() IS NULL;
update GEBOUWINSTALLATIE_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update GEMEENTE_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update INRICHTINGSELEMENT_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update KAD_PERCEEL_ARCHIEF c set BEGRENZING_PERCEEL = null where c.BEGRENZING_PERCEEL.GET_GTYPE() IS NULL;
update KAD_PERCEEL_ARCHIEF c set PLAATSCOORDINATEN_PERCEEL = null where c.PLAATSCOORDINATEN_PERCEEL.GET_GTYPE() IS NULL;
update KUNSTWERKDEEL_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update ONBEGR_TERR_DL_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update ONBEGR_TERR_DL_ARCHIEF c set KRUINLIJNGEOM = null where c.KRUINLIJNGEOM.GET_GTYPE() IS NULL;
update ONDERSTEUNEND_WEGDEEL_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update OVERIG_BOUWWERK_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update OVRG_SCHEIDING_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update PAND_ARCHIEF c set GEOM_BOVENAANZICHT = null where c.GEOM_BOVENAANZICHT.GET_GTYPE() IS NULL;
update PAND_ARCHIEF c set GEOM_MAAIVELD = null where c.GEOM_MAAIVELD.GET_GTYPE() IS NULL;
update SCHEIDING_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update SPOOR_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update STADSDEEL_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update VRIJSTAAND_VEGETATIE_O_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WATERDEEL_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WATERSCHAP_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WEGDEEL_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WIJK_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update WNPLTS_ARCHIEF c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;
update BEGR_TERR_DL c set KRUINLIJNGEOM = null where c.KRUINLIJNGEOM.GET_GTYPE() IS NULL;
update BEGR_TERR_DL c set GEOM = null where c.GEOM.GET_GTYPE() IS NULL;

**Comment by mprins** [comment]
De beste oplossing in de code hiervoor zit in de upgrade van GeoTools naar een versie 16 (of mogelijk 15.2 - zie: geotools/geotools#1312),  daarvoor is wel een upgrade naar java 8 nodig ( #220 )
