### ISSUE TITLE
BRT/TOP10NL inladen in apart schema

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#231]
De BRMO wordt uitgebreid met TOP10NL met de bijbehorende TOP50NL, TOP100NL en TOP250NL en TOPGRENZEN in apart schema.
Het GML van deze bestanden is vergelijkbaar en uitgezocht moet worden of dit allemaal via de zelfde parser kan worden gedaan. SLD's zijn beschikbaar (bv JWvA). Drenthe levert SLD's aan voor TOP50NL, TOP100NL en TOP250NL.

**Comment by mtoonen** [comment]
Gefixt in #344
