### ISSUE TITLE
Bij omzetting van een persoon naar een ingeschr. nat. persoon gaat bsn verloren

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#267]
Indien een persoon eerst als ander natuurlijk persoon wordt opgenomen in de database en later de status verandert naar ingeschreven natuurlijk persoon, dan wordt de extra informatie (i.e. BSN) niet geupdatet.

**Comment by cvanlith** [comment]
Dit komt omdat in de code onvoldoende wordt gecheckt of een record al bestaat. Elke insert/update moet vooraf gegaan worden door zo'n check.

**Comment by cvanlith** [comment]
opgelost via 834e3d5e4dea8b80804ab18bd89b316ddffaa42f

**Comment by mprins** [comment]
Is de (data) fix hiervoor het draaien van de "snelle update" voor BSN? dan kan dat in de release notes voor 1.4.1
