### ISSUE TITLE
1.4.1 - Verwacht standaard RSGBBGT-datasource

### ISSUE THREAD

**Issue by reinderhoekstra** [B3Partners/brmo#271]
In versie 1.4.1 is terug wat in 1.4.0 niet zat (en in een oudere versie dan 1.4.0 (welke weet ik niet meer) weer wel), nl. dat de brmo-service-tomcat-webapp standaard een Resource name="jdbc/brmo/rsgbbgt verwacht. Bij provincie Overijssel is dit schema niet aanwezig in de oracle-database. Dit lijkt overigens een juiste werking niet in de weg te staan van de webapp, hoewel ik dat ook niet goed kan overzien.

**Comment by mprins** [comment]
in 1.4.1 is versiecontrole van de schema's/databases toegevoegd; als het ophalen van de versie uit een schema/database mislukt dan wordt daar een (verbindings-) fout voor gelogd in de `brmo-service.log` in de trant van "Versienummer kon niet uit de RSGBBGT database worden gelezen.", maar verder zijn daar geen consequenties. De versienummering is een eerste stap op de weg om automatische schema upgrades mogelijk te maken.

Het ontbreken van een rsgbbgt schema staat wel bepaalde manieren van (oa. laadproces gestuurde) bericht transformatie in de weg, maar het kan zijn dat je die niet gebruikt en het dus geen probleem vormt.

**Comment by mprins** [comment]
eea is verduidelijkt in de installatiehandleiding; in de toekomst gaan we waarschijnlijk naar een schema per registratie zodat het makkelijker is om he RSGB schema te upgraden en resources beter te benutten
