### ISSUE TITLE
Relatie tussen appartement en grondperceel niet altijd helder

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#315]
In de BRK bestaat een rechtstreekse relatie tussen een appartement en het bijbehorende grondperceel. Kadaster zelf raadt aan deze relatie te leggen via de VVE. Echter in ca. 2% van de gevallen is geen VVE opgegeven bij het appartment. Als dit wel het geval is dan kan via de zakelijk recht tabel opgezocht worden bij welke rechten (eigendom, erfpacht e.d.) de VVE betrokken is. Zo kan dan het bijbehorende grondperceel gevonden worden.
B3Partners gebruikt tot nu toe een andere methode. Via documenten wordt opgezocht hoe een appartement is ontstaan: via splitsing en ondersplitsing. Zo kan terug gezocht worden bij welk grondperceel de splitsing oorspronkelijk begon. Hierbij wordt telkens gezocht naar een paar van BetrokkenBij en OntstaanUit documenten. Nu blijkt dat ook hierbij problemen ontstaan. Onderzoek wijst uit dat OntstaanUit Ondersplitsing niet altijd gekoppeld kan worden aan een BetrokkenBij Ondersplitsing document.
De methodiek is nu aangepast dat bij het terugzoeken van een grondperceel vanaf een ondersplitsingssituatie ook gekoppeld wordt met een BetrokkenBij Hoofdsplitsing, natuurlijk wel in de zelfde akte.

**Comment by cvanlith** [comment]
Via commit f8b3171e8b289b4e04b3e6821f9709161343167c zijn de views aangepast

**Comment by mprins** [comment]
@cvanlith ik neem aan dat de upgrade scripts nog gedaan moeten worden hiervoor? zal ik die oppakken?
