### ISSUE TITLE
Bij meervoudige ondersplitsing blijft de tussensituatie ook bestaan in de koppelview

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#331]
Bij meervoudige ondersplitsing blijft de tussensituatie ook bestaan in de koppelview tussen perceel en appartement. Indien een appartement is ondergesplitst dan moet het oorspronkelijke appartement niet meer worden meegenomen in de views voor o.a. de eigenarenkaart,

**Comment by mprins** [comment]
zie [mantis 6381](http://mantis.b3p.nl/view.php?id=6381)
