### ISSUE TITLE
Mutatie van rechten bij een commanditair vennootschap niet correct

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#332]
Een bericht van kadaster (gecontroleerd bij Kadaster dat het bericht correct is) wordt door de BRMO niet correct verwerkt. Het probleem lijkt te zitten in het toegepaste commanditair vennootschap. De voormalige rechthebbende was de provincie Limburg voor 100%. Nieuwe rechthebbende is een CV waarin de provincie voor 19/25-deel participeert en de gemeente Venlo voor 6/25-deel. Nu is een CV geen rechtspersoon dus de rechten gaan pro rato naar de deelnemers in de CV.
De provincie Limburg is daarmee zowel voormalig rechthebbende als ook nieuw rechthebbende, echter in de nieuwe situatie voor een kleiner deel. Dit wordt door de BRMO niet correct verwerkt.

**Comment by cvanlith** [comment]
zie mantis 6380

**Comment by mprins** [comment]
De oorzaak hiervan zit in het verwijderen van het voorgaande (stand) bericht althans de db_xml daarvan waardoor de mutatie als stand wordt verwerkt
