### ISSUE TITLE
Gebruik aantal uitgevoerde updates als extra check bij updaten

### ISSUE THREAD

**Issue by mtoonen** [B3Partners/brmo#34]
Had een inconsistente database (er zat niks in prs, maar wel in subject). Aanschouw het volgende:
```
Controleer subject op primary key: [NL.KAD.Persoon.157343790], rij bestaat: ja
SQL: update subject set IDENTIF = ?, CLAZZ = ? WHERE identif = ?, params ([NL.KAD.Persoon.157343790, INGESCHREVEN NATUURLIJK PERSOON]), pkeys ([identif=NL.KAD.Persoon.157343790] )
SQL: update prs set SC_IDENTIF = ?, CLAZZ = ? WHERE sc_identif = ?, params ([NL.KAD.Persoon.157343790, INGESCHREVEN NATUURLIJK PERSOON]), pkeys ([sc_identif=NL.KAD.Persoon.157343790] )
```
Alles lijkt goed te gaan, maar bij de update van prs zal geen update uitgevoerd gaan worden (results is 0), wat op een fout duidt. 

Misschien is het voor de volledigheid goed om hier een melding van te geven (hoewel het natuurlijk niet voor moet komen dat er een inconsistente db is).

**Comment by cvanlith** [comment]
procesflow verbeterd zodat dit niet voor zou mogen komen
