### ISSUE TITLE
Optimalisatie ten bate van Oracle cursor probleem

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#345]
Hoewel de code theoretisch geen probleem met Oracle cursors zou moeten hebben, alle resultsets worden netjes gesloten, blijft dit probleem toch telkens weer opduiken. Googlelen levert op dat mogelijk de garbage collection van Java niet snel genoeg is. Oplossing: Runtime.getRuntime().gc(); Ik weet niet of dit een goed idee is in verband met de snelheid.
Nog een keer de code doornemen levert op dat voor elke insert/update op de database een bestaat-record-select wordt gedaan, waarvoor een cursor nodig is in Oracle. Dit kan per bericht in de duizenden keren lopen. Mogelijke oplossing is per bericht vooraf in één select-statement alle relevante records op te halen, zodat maar één cursor nodig is. Deze records worden in het geheugen gecached en tijdens het schrijven naar de RSGB-database wordt het bestaan in de cache gecheckt.
Dit kan duizenden select statements schelen en mogelijk het cursor-probleem oplossen.

**Comment by cvanlith** [comment]
Het gaat om de methodes rowExistsInDb en isAlreadyInMetadata als gebruikt in de methode parseNewData.

**Comment by mprins** [comment]
zie f1cf88c979cb394eedfa9fa73729c6a26f0ed14b

**Comment by mprins** [comment]
> Ik heb vanmorgen een transformatieproces gestart met alle 17.035 mutatieberichten en deze zijn â€“weliswaar een stuk langzamer dan normaalâ€“ allemaal succesvol gemuteerd in de RSGB database zonder foutmeldingen. De snelheid maakt niet zoveel uit, als we er maar vanuit kunnen gaan dat de mutatieberichten automatisch en zonder storing in de database verwerkt worden.

[mantis 6467](http://mantis.b3p.nl/view.php?id=6467) resolved
