### ISSUE TITLE
Upgrade van comfort naar authentiek weer inschakelen

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#346]
Indien informatie eerst als comfort informatie aan de rsgb is toegevoegd, dan wordt een herkomst-metadata record gevuld om dit aan te geven. Als later de dezelfde info via een andere basisregistratie als authentieke informatie binnenkomt, dan dient het record uit de herkomst-metadata-tabel verwijderd te worden. Op dit moment is dit stukje code uitgecomment: [RsgbProxy regel 707](https://github.com/B3Partners/brmo/blob/master/brmo-loader/src/main/java/nl/b3p/brmo/loader/RsgbProxy.java#L707).
Graag deze code weer inschakelen nu BRP en NHR geladen gaan worden.

**Comment by mprins** [comment]
dit zit in f1cf88c979cb394eedfa9fa73729c6a26f0ed14b

Maar een testcase zou mooi zijn, bijv. een brk (stand) bericht met een niet natuurlijk persoon en een nhr bericht dat er achteraan komt voor die persoon
