### ISSUE TITLE
PDOK tileinfo.json is leeg

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#367]
PDOK is gestopt met publiceren, althans van publiceren met inhoud, van de url https://www.pdok.nl/download/service/tileinfo.json?dataset=bgt&format=citygml daardoor kan de BGT download job niet meer bepalen wat de grid ids zijn er kan er niet meet op basis van een polygoon worden gedownload.

mogelijk kunnen we de logica nog eens reverse-engineeren.

**Comment by mprins** [comment]
in de testcase voor de job zit de oorspronkelijke geojson; testen of die nog correct is en dan opnemen in de applicatie

- https://github.com/B3Partners/brmo/blob/master/bgt-gml-loader/src/test/resources/geojson/tileinfo.json
- https://github.com/B3Partners/brmo/blob/master/bgt-gml-loader/src/test/resources/geojson/tileinfo.geojson

**Comment by matthijsln** [comment]
Formule hier https://forum.pdok.nl/t/formule-berekening-tegelnummer-download-bgt/658

**Comment by mprins** [comment]
Ik heb een geopackage met de grids, moet alleen even een geojson exporteren

**Comment by mprins** [comment]
de geojson is per direct beschikbaar op: `http://files.b3p.nl/brmo/bgt/tileinfo.geojson`
