### ISSUE TITLE
Bij handmatig uitvoeren proces wordt log niet bijgewerkt

### ISSUE THREAD

**Issue by matthijsln** [B3Partners/brmo#40]

**Comment by mprins** [comment]
Ook voor de bericht transformaties. 
De TransformActionBean heeft geen benul van een automatisch proces (dezelfde call gebruikt als de "Alles transformeren naar RSGB" op de berichten pagina)

Mogelijk oplossen met een extra action bean of methode die wel kennis heeft van een AutomatischProces.

**Comment by matthijsln** [comment]
Bij het transformeren is het log niet zo belangrijk. Dat komt in elk bericht record apart te staan.
