### ISSUE TITLE
Afgiftes ophalen met selectiecriteria periode van/tot

### ISSUE THREAD

**Issue by matthijsln** [B3Partners/brmo#46]
Wel ervoor zorgen dat er niet meer dan 2000 afgiftes binnen de periode vallen. Zo niet afhankelijk van 'al gerapporteerd' status.

**Comment by mprins** [comment]
opgelost met da2969ed6d4a76bf08d19b61999a4d5a1efe0239 en dd1620fcd0b2b29ffd587a9c8a35a8727a3e9c0a
