### ISSUE TITLE
BGT tabellen worden leeggemaakt tijdens laden van data

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#541]
### Probleem
Tijdens laden van de BGT worden tabellen leeggemaakt; 1 keer leegmaken is goed, maar nu gebeurd dat voor elk bestand, niet handig want dan is alleen het laatst geladen kaartblad aanwezig na afloop

### Versie
versie info:  1.6.0

zie ook [mantis 12289](http://mantis.b3p.nl/view.php?id=12289)

**Comment by matthijsln** [comment]
Zie #542
