### ISSUE TITLE
Fout bij deployen 1.2.1 release op Java 6

### ISSUE THREAD

**Issue by matthijsln** [B3Partners/brmo#55]
SEVERE: Error deploying web application archive brmo-service.war
java.lang.UnsupportedClassVersionError: org/javasimon/console/SimonConsoleServlet : Unsupported major.minor version 51.0 (unable to loa
        at org.apache.catalina.loader.WebappClassLoader.findClassInternal(WebappClassLoader.java:2822)

**Comment by mprins** [comment]
miv versie 1.2.11 is java 7 de minimum vereiste versie voor de brmo
