### ISSUE TITLE
zoeken op datum in archief views is erg langzaam

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#596]
### Probleem
Bijvoorbeeld jongste archief perceel van een set vinden of mutaties van afgelopen 90 dagen

mogelijk een GiST index gebruiken, zie: https://www.postgresql.org/docs/current/gist-builtin-opclasses.html#GIST-BUILTIN-OPCLASSES-TABLE

### Versie
versie info: 1.6.0 - 1.6.3 - 1.6.4-SNAPSHOT

**Comment by mtoonen** [comment]
Is dit nog relevant? In de nieuwe views wordt nu de juiste cast gebruikt, waardoor de index gebruikt wordt

**Comment by mprins** [comment]
ik denk dat dit opgelost is met de "datum" type kolommen in de views, mogelijk moet daar nog een index op gezet worden dan..

ik zal eens kijken, alle "jongste" archief percelen zitten nu in een view

**Comment by mprins** [comment]
niet langer een probleem
