### ISSUE TITLE
Monitoring tool geeft geen waarde van de status RSGB_OK en RSGB_NOK

### ISSUE THREAD

**Issue by Sjoske** [B3Partners/brmo#604]
### Probleem
Monitoring tool geeft geen waarde van de status RSGB_OK en RSGB_NOK als er veel berichten inzitten. 
Krijgt dan een time-out en geeft de waarde -1 aan.

### Versie
Versie: | 1.6.2                                                                               (laatste release: v1.6.3, dd. Tue Jan 08 2019)

**Comment by mprins** [comment]
Het kan zijn dat de queryTimeout het niet goed is ingesteld (normaal doen we dat helemaal niet) of de database te langzaam is omdat de tabel niet ge-vacuum-ed en/of -ge-analyze- d en/of de index out-of-date is.

voor tomcat 8.5.x zin de params te vinden op: https://commons.apache.org/proper/commons-dbcp/configuration.html  (`defaultQueryTimeout`)

**Comment by Sjoske** [comment]
Bij de tabel "Bericht" de reindex optie aan gezet. Alle overige tabellen de optie vacuum aangezet
