### ISSUE TITLE
RSGB_OUTDATED graag splitsen in RSGB_OUTDATED_BAG en RSGB_OUTDATED_REST

### ISSUE THREAD

**Issue by Sjoske** [B3Partners/brmo#605]
### Probleem
De tabel RSGB_OUTDATED bevat zowel de berichten van de BAG als van de BRK/NHR.
Aangezien in de BAG de meeste fouten komen, is het handig als dit in een aparte tabel komt

### Versie
1.6.x

**Comment by mprins** [comment]
Er is geen tabel RSGB_OUTDATED, er is een tabel met berichten en ieder bericht heeft een status. 
De RSGB_OUTDATED status is een uitzonderlijke status die weinig voorkomt / weinig voor mag komen in normale operatie en een indicatie dat er dingen fout zijn gelopen bij het laden van data, als er veel zijn dan moet het werkproces tegen het licht worden gehouden.

Het toevoegen van extra status is niet triviaal en zou dan voor ieder soort bericht gedaan moeten worden, niet met een "rest" catagorie, bovendien dupliceert dat dan een gegeven dat al beschikbaar is in het datamodel van de bericht tabel.
