### ISSUE TITLE
MB_PAND toont ook gesloopte panden

### ISSUE THREAD

**Issue by Sjoske** [B3Partners/brmo#606]
### Probleem
Voor de BAG gebruiken wij de BRMO voor het verwerken van mutaties en
> maken we gebruik van de view MB_PAND om de BAG panden in zowel ArcGIS
> als onze provinciale viewers te ontsluiten.
>
> Nu is ons opgevallen dat er voor de view MB_PAND geen filter wordt
> toegepast op STATUS van het pand. Dit resulteert in ongeveer 70.000
> panden voor de provincie Limburg welke in feite gesloopt zijn (en ook
> niet meer voorkomen in de BAG viewer van het Kadaster), maar bij ons
> nog voorkomen in de database. Doordat de view deze niet weg filtert
> komen ze ook op kaart te staan.
>
> We zijn dan ook erg benieuwd naar de reden waarom de view ook
> gesloopte panden bevat. Is hier een bepaalde reden voor waarom de
> gesloopte panden –anders dan de officiële BAG viewer van het Kadaster–
> in de view van B3Partners worden getoond of betreft dit een fout in de
> view?

### Versie
versie 1.6.1

### Server log
https://mantis.b3p.nl/view.php?id=12765

**Comment by mprins** [comment]
Ik weet niet waarom de view is zoals deze is (missschien weet @cvanlith dat), de view definties zijn in/met de gebruikersgroep opgesteld, ik ga ervan uit dat dit een bewuste keuze is. Zie verder:

- https://github.com/B3Partners/brmo/wiki/view_v2_definities
- https://github.com/B3Partners/brmo/wiki/view_v2_definities#view-vb_pand
- https://github.com/B3Partners/brmo/wiki/basisviews_v2_commentaar
- de verslagen van de afgelopen gebruikersgroep bijeenkomsten: https://github.com/B3Partners/brmo/wiki/Gebruikersoverleg-BRMO

Gebruiker kan zelf het filter toevoegen in de database als maatwerk view of in de applicatie die de view gebruikt, (daarom zit `status` in de view).
