### ISSUE TITLE
Bijwerken van de basisviews obv gebruikersopmerkingen

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#615]
- [x] In MB_SUBJECT veld GESLACHTSAAND worden komen drie waarden voor; M, V en 3. Moet die 3 niet vervangen worden door X? Als we kijken naar de BRP dan is hier de categorie ‘Onbekend’ bijgekomen met een aanduiding X.
- [x] In MB_ZR_RECHTH zit een typefout in de kolomnaam OMSCHR_AARD_VERKREGENR_RECHT (er staat een R teveel).
- [x] We missen een view waarin unieke onroerende zaken zitten (percelenkaart). Om een view met unieke percelen te genereren moeten we alsnog een view maken wat ten koste gaan van de performance (unieke identifiers voor KOZ of ZR eruit filteren en adresgegevens verbergen).
  - nieuwe poging tot percelenkaart mb_percelenkaart, het blijft onduidelijk wat er precies in de percelenkaart moet zitten.
- [x] Er is geen materialized view beschikbaar voor de kadastrale aantekeningen op een onroerende zaak of op een zakelijk recht.
  - de aantekeningen zijn samengevoegd in een tekstveld geplaatst
- [x] Een van de bevindingen daarbij is dat Postgres velden die numeric zijn en kleiner dan 10 digits niet goed worden weergeven in Arcgis (laat 0 ziet ipv waarde). Dit is een known issue bij Esri: numeric(10,0)
  - dit is op bijna 50 plaatsen aangepast naar INTEGER(10), graag testen of we alles gevonden hebben en of het bij esri werkt
- [x] datums in de views niet alleen als tekst, opzoeken van historische (brk) gegevens is nu erg langzaam omdat datum geldigheid als text in de views (want ook in de tabellen) staat.
- [x] vb_benoemd_obj_adres en vb_vbo_adres:  gebruiksdoelen van het verblijfsobject toevoegen, gebruiksoppervlakte toevoegen, aanduiding hoofd- nevenadres 
  - alleen hoofdadressen
- [x] VB_adres: Status, Aanduiding hoofdadres
  - dit zijn alleen hoofdadressen, voor nevenadressen zie ...ben_obj_nevenadres
- [x] VB_BEN_OBJ_NEVENADRES: Status

**Comment by cvanlith** [comment]
Deze verzoeken wordt niet ingewilligd:
- [ ] In MB_ZR_RECHTH ontbreekt het veld TYPE (perceel of appartementsrecht). Dit veld zou je willen kunnen gebruiken om op type onroerende zaak te filteren.
  - type wordt pas bekend bij koppelen met onroerende zaak, daar is type wel beschikbaar

**Comment by mprins** [comment]
@cvanlith land wordt meestal niet gevuld omdat verschillende BR's verschillende codelijsten gebruiken, 2-letter ISO code in rsgb maar andere lijsten in verschillende BR's (bijv. NL overheid landcodes), "land" en "nationaliteit" is dus meestals niet gevuld in de tabellen.
zie ook: 

BRK

https://github.com/B3Partners/brmo/blob/8a08ac8be2faa536d54c941cd9b9bd0f6ba3f699/brmo-loader/src/main/resources/xsl/brk-snapshot-to-rsgb-xml.xsl#L515-L517

https://github.com/B3Partners/brmo/blob/8a08ac8be2faa536d54c941cd9b9bd0f6ba3f699/brmo-loader/src/main/resources/xsl/brk-snapshot-to-rsgb-xml.xsl#L635-L642

https://github.com/B3Partners/brmo/blob/8a08ac8be2faa536d54c941cd9b9bd0f6ba3f699/brmo-loader/src/main/resources/xsl/brk-snapshot-to-rsgb-xml.xsl#L682-L686

BRP

https://github.com/B3Partners/brmo/blob/8a08ac8be2faa536d54c941cd9b9bd0f6ba3f699/brmo-loader/src/main/resources/xsl/gbav-to-rsgb-xml.xsl#L10-L12

https://github.com/B3Partners/brmo/blob/8a08ac8be2faa536d54c941cd9b9bd0f6ba3f699/brmo-loader/src/main/resources/xsl/gbav-to-rsgb-xml.xsl#L527-L535

**Comment by mprins** [comment]
#617 is gemerged
