### ISSUE TITLE
Geen verversing status bij handmatig transformeren bij de automatische processen

### ISSUE THREAD

**Issue by Sjoske** [B3Partners/brmo#759]
### Probleem
Indien je handmatig de functie transformeren gebruikt bij de automatische processen wordt de status niet veranderd

### Versie
versie info: 1.5.2.5 tot en met 2.0.0

**Comment by mprins** [comment]
@Sjoske  Als je "BerichtTransformatieUitvoeren" of "LaadprocesTransformatieUitvoeren" handmatig start vanuit Automatische Processen pagina? 

Status zou moeten worden bijgewerkt op de Automatische Processen pagina, maar daarvoor moet wel deze pagina worden ververst nadat eea in de staging database is opgeslagen, kan zijn dat het in de queue komt en dus pas na afloop van verwerking wordt vastgelegd... 
in ieder geval is er dan toch de gewone voortgangspagina?...
